#! /bin/sh
#
# DCTAB bring-up script
#		It is called from the boot script.
#
# Version:	
#

case "$1" in
	start|"")
		printf "Starting S01dctab: "




		;;
	stop)
		printf "Stopping S01dctab: "

		;;
	*)
		echo "Usage: $0 {start|stop}" >&2
		exit 1
		;;
esac

exit $?
